module.exports = {
    purge: ["./pages/**/*.tsx", "./src/**/*.tsx"],
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {
            fontSize: {
                // navBar: ""
                6: ["0.6rem"],
                7: ["0.7rem"],
                8: ["0.8rem"],
                9: ["0.9rem"],
                10: ["1rem"],
                11: ["1.1rem"],
                12: ["1.2rem"],
                13: ["1.3rem"],
                14: ["1.4rem"],
                15: ["1.5rem"],
                16: ["1.6rem"],
                17: ["1.7rem"],
                18: ["1.8rem"],
                19: ["1.9rem"],
                20: ["2rem"],
                24: ["2.4rem"],
                28: ["2.8rem"],
                32: ["3.2rem"],
                36: ["3.6rem"],
                40: ["4rem"],
                44: ["4.4rem"],
                48: ["4.8rem"],
                52: ["5.2rem"],
                56: ["5.6rem"],
                60: ["6rem"],
                64: ["6.4rem"],
                68: ["6.8rem"],
                72: ["7.2rem"],
                96: ["9.6rem"],
                128: ["12.8rem"],
            },
        },
    },
    variants: {
        extend: {},
    },
    plugins: [],
};
